version: '3.9'

services:
  api: &default
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: ['/usr/src/app/entrypoint.sh']
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db

  test: &test
    <<: *default
    command: python -m pytest -v "src/tests"


  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
